# Generated by Django 5.2.6 on 2026-02-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atm', '0001_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmtoken',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account'),
        ),
    ]
