# Generated by Django 5.2.6 on 2026-02-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_initial'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmtoken',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banking.account'),
        ),
    ]
